language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
before_install:
- npm install -g greenkeeper-lockfile@1
before_script:
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
- npm run coverage
- npm run codeclimate
env:
  global:
  - secure: fu9UQzNA+EssnEMZF1rxD0UvX4rJeAaz1F0POz5fr3pK/Mmuou3acDXwbW78Jf6hXHhNtfnl99fR8XE49qWzmdorN4XMSuGZWA4CBu4njAsO8ucq3TyhHhTSHJwHtvoC0jZjDxrxo+o8s5+XwDO77r2cwyj6dltFDXdv0YperKOFqfc8GN90nocYqjLFzJt3xLpsO69rHGHijFB1lrOlgTmsoSF90m0E4aN91+N4nUNSSnt4pRUgjivzGnxuRWt8+aSOHg+IvHC5zIb+6+zCv5EbxVbpNI5LzIjgdRTJ+JOdSEXZSsRUxd7IfcDYS207w7Df9Cz8R9pQ9aIIQ7SKN50Z7gi7U2BuMaJtzkzGGsoy3D/Itrx8bM6tOGENm6Okbn2UOCSmaRcs3YEuVYFwfR0qeWfY+2mwmDxSjqnsDZ1RWgxLAPMcB3qnSCAMxd9nElFBaapYMQBrBXNSUnPzt6UzhyrXoasJVc1eDihb5Y6uOpuG6lknuy5n2YfTeTKQbZhNhyp+kBCGw1LDIj1J+cV/etBu512B5OhBtJnyO/dzAPyWsB9dHPyqWDFASFOhSJ9Djzcpy9I8VhGkcD7eTvRMm+D+5L2jiAbD48r7KGhbKFdKMfKZBI0dJXV5SFirKOKlqvvhOM4Fo1h8RMSCK5ng0zj+mI7colbLfkuPU+U=
  - secure: AN+0IYcfJWIT7nmvLfa5ZDrNEWHNWbRMsqo4CQ+zDnpkcJLqdKjVbQYyZ7fgxD0EiqG8PYVc4qizeNlASBI8SrCkMMf6yszVvwTvbmqOLzwbrC6fE6A7E4h5QVYOYu30ThwiTKTAfN09+kF8D0c8daVJJcf3Junf7AdsqqzMU3Mur65OBMxVDHd0D01GvqBiddU4NRduQxeJ3soxr2ad1jZIKc+gMPQNZY5bThsY2ygawUV4IYv0+VOnHZpzTY4aIvSeLJqAz/xNHieptsEz0qLOJ7nQeDZjW3KH//wPbjDsEmNiREQBLUylcj1t6P69st7+CJg1Z/prwcrY5rleLxjVlScgCIflFyLkYG2bjpAF/YUCL/9RRqzAGk3SIyngM7/0YYchduBqNwJm/xe5kbsnqstHu4ZC4IDXU5fc1N9EWc9kVNh1GxqbBotrlb48twvB9PFC5pcoMPoVEN3t5oncRKwZ6PW9DODez9OGbgelO7kXcnjMLweB2gEEfgNinnz/aAzu7r7e6qJ/ViiUPK9yffNY2uS7hVPHb3XlbPYXnTgcBu34riCNSRgvH61JpHLkCHxrNnzFEHHpHNSjk92p8QUdjrtQ8Ew779dcz7zlBCSuBrO/HLQKp3nB3Kh/uvNV723KPzpf857gwqFt8EsWFMaSJtwdf9+G2iIGdbk=
