language: node_js
os:
  - linux
  - windows
node_js:
  - lts/*
notifications:
  email:
    on_success: change
    on_failure: change
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      npm run build:windows;
    else
      npm run build;
    fi
after_script:
  - codecov
stages:
  - "Test"
  - name: "Deploy"
    if: branch = master AND repo = smockle/contrast
matrix:
  allow_failures:
    - os: windows
jobs:
  include:
    # DEPLOY
    - stage: "Deploy"
      name: "Deploy"
      script: skip
      before_deploy: npm run _version
      deploy:
        - provider: npm
          skip_cleanup: true
          email: bot@smockle.com
          api_key:
            secure: A7ZnJePZl4zOc/wTk+A1khzXUly05MBDkCeXDf/BgZVn8EO3jBn+clx4jfrpZjLoy3dDC8zwGUWXsqF2D4CkaewsvR+j+nHei59G1+q+Riki/AoslzTreS4HJNd6+Phpb5wNROp6AnDmpQLgSIT88f11gD8g3MQQRwhdeHNRam0pxpIysUU7S9EatgZQG+PDRu6sAybqcsu+JsSIr4BlMWO1YCsmxhDQH43ldPkAR8ubxbx2zO4D+cmS2JTFtLFA+neipoAH08TJbjrrMkQI/CElT59bTm81avyGbaqDR0Ua9GS4H7WpBZ9El1fbOq9FBNibSyx7BIXNQz/d17EDcV9Trp1unLPWWJ8HAtChzCEMhc1tmPL6ug1AalIV/z3Son+7GOZj2DgvF4VclqHEHXpbPca3u9yqna2p7tzSOhoIr3+Sd2nbV+NnA+H4lwFjrIzZ8cBScJNamQ3Vem9S7fs2FMev01wBTtNA6r3RD9ZKN80K54zAgcq9YPnK+uNgySVQPYQnyinGLluZ9e8CpnCChJsgy0YMma+vsC/qZofaxT+Pj4WnXltkkHoTGJZd87bjyy5YWndEd3fysWRbuxgQaF/aEkdAbrTTb/cJCXRMQXAL3qrKZG9bbv+S18yFG52fL4oTXU/w/vsFoGIL5+m+W+XQF/YnkDuUJE2qszo=
          on:
            branch: master
            repo: smockle/contrast
            tags: false
