language: node_js
node_js:
- '8'
- '6'
notifications:
  email:
    on_success: change
    on_failure: always
after_script:
- npm run coverage
- npm run codeclimate
env:
  global:
    secure: fu9UQzNA+EssnEMZF1rxD0UvX4rJeAaz1F0POz5fr3pK/Mmuou3acDXwbW78Jf6hXHhNtfnl99fR8XE49qWzmdorN4XMSuGZWA4CBu4njAsO8ucq3TyhHhTSHJwHtvoC0jZjDxrxo+o8s5+XwDO77r2cwyj6dltFDXdv0YperKOFqfc8GN90nocYqjLFzJt3xLpsO69rHGHijFB1lrOlgTmsoSF90m0E4aN91+N4nUNSSnt4pRUgjivzGnxuRWt8+aSOHg+IvHC5zIb+6+zCv5EbxVbpNI5LzIjgdRTJ+JOdSEXZSsRUxd7IfcDYS207w7Df9Cz8R9pQ9aIIQ7SKN50Z7gi7U2BuMaJtzkzGGsoy3D/Itrx8bM6tOGENm6Okbn2UOCSmaRcs3YEuVYFwfR0qeWfY+2mwmDxSjqnsDZ1RWgxLAPMcB3qnSCAMxd9nElFBaapYMQBrBXNSUnPzt6UzhyrXoasJVc1eDihb5Y6uOpuG6lknuy5n2YfTeTKQbZhNhyp+kBCGw1LDIj1J+cV/etBu512B5OhBtJnyO/dzAPyWsB9dHPyqWDFASFOhSJ9Djzcpy9I8VhGkcD7eTvRMm+D+5L2jiAbD48r7KGhbKFdKMfKZBI0dJXV5SFirKOKlqvvhOM4Fo1h8RMSCK5ng0zj+mI7colbLfkuPU+U=
