language: node_js
node_js:
  - "8"
notifications:
  email:
    on_success: change
    on_failure: always
before_script:
  - npm run build
after_script:
  - codecov
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run _version
    on:
      branch: master
      repo: smockle/contrast
      tags: false
  - provider: npm
    skip_cleanup: true
    email: bot@smockle.com
    on:
      branch: master
      repo: smockle/contrast
      tags: false
